export const productData = [
    {
        id: 22,
        asin: "B083JM36RQ",
        title: "Taste Beauty Pepsi Wild Cherry Flavored Lip Balm",
        amazonImage: "https://m.media-amazon.com/images/I/71e3jwUefGL._SX466_.jpg",
        supplierImage: "https://usabites.co.uk/cdn/shop/products/PepsiWildCherry-800x800.png?v=1681811179&width=823",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B083JM36RQ",
        amzPrice: "$10.99",
        storePrice: "$2.00",
        amazonLink: "https://www.amazon.com/dp/B083JM36RQ",
        storeLink: "https://usabites.co.uk/products/taste-beauty-pepsi-wild-cherry-lip-balm?srsltid=AfmBOoqYSBfDZ0p1xhnhRoPyeolOyfSMDi5xasgP-b06aJku-TBGvmRJ",
        salesRankDrops: "3.44",
        roi: "23.9",
        profit: "$1.09"
    },
    {
        id: 23,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ogt/ogt00086/l/2.jpg",
        keepaChart: "https://graph.keepa.com/graph.png?asin=B084RRSBX4&domain=1&amazon=1",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://uk.iherb.com/pr/organic-traditions-instant-mushroom-coffee-focus-fuel-5-oz-140-g/138741",
        salesRankDrops: "16.51",
        roi: "34.16",
        profit: "$6.51"
    },
    {
        id: 24,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cdn.dolphinfitness.com/tn1/tn1_148276722.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B084RRSBX4",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://www.dolphinfitness.co.uk/en/natural-traditions-focus-fuel-coffee-140g/276722",
        salesRankDrops: "17.59",
        roi: "26.95",
        profit: "$5.43"
    },
    {
        id: 26,
        asin: "B0CVQSDDZJ",
        title: "Panini FIFA 2024 Top Class Blaster Box, Mixed",
        amazonImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL.__AC_SX300_SY300_QL70_ML2_.jpg",
        supplierImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL._AC_SX425_.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0CVQSDDZJ",
        amzPrice: "$28.87",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        storeLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        salesRankDrops: "11.49",
        roi: "42.01",
        profit: "$6.11"
    },
    {
        id: 27,
        asin: "B0BDBCQQW2",
        title: "Ultra Pro | Pokemon Pikachu & Mimikyu 9-Pocket Folder",
        amazonImage: "https://m.media-amazon.com/images/I/81t8iT1SxOL._AC_SX425_.jpg",
        supplierImage: "https://cdn.chaoscards.co.uk/uploads/prod_img/2_220505_e.png?v=-62169983925",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0BDBCQQW2",
        amzPrice: "$28.26",
        storePrice: "$3.00",
        amazonLink: "https://www.amazon.co.uk/Ultra-Pro-Pokemon-Pikachu-Mimikyu/dp/B0BDBCQQW2",
        storeLink: "https://www.chaoscards.co.uk/prod/folders/ultra-pro-pokemon-pikachu-mimikyu-9-pocket-a4-portfolio",
        salesRankDrops: "8.51",
        roi: "45.82",
        profit: "$5.98"
    },
    {
        id: 28,
        asin: "B000RY496K",
        title: "Yankee Candle French Vanilla Small Jar Candle",
        amazonImage: "https://m.media-amazon.com/images/I/518hWlJopTL._AC_SX679_.jpg",
        supplierImage: "https://www.candleemporium.co.uk/images/productzoom/1507745E.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B000RY496K",
        amzPrice: "$20.86",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Yankee-Candle-French-Vanilla-Small/dp/B000RY496K",
        storeLink: "https://www.candleemporium.co.uk/yankee-candle-vanilla-small-jar/p/11008/",
        salesRankDrops: "6.89",
        roi: "24.39",
        profit: "$2.66"
    },
    {
        id: 22,
        asin: "B083JM36RQ",
        title: "Taste Beauty Pepsi Wild Cherry Flavored Lip Balm",
        amazonImage: "https://m.media-amazon.com/images/I/71e3jwUefGL._SX466_.jpg",
        supplierImage: "https://usabites.co.uk/cdn/shop/products/PepsiWildCherry-800x800.png?v=1681811179&width=823",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B083JM36RQ",
        amzPrice: "$10.99",
        storePrice: "$2.00",
        amazonLink: "https://www.amazon.com/dp/B083JM36RQ",
        storeLink: "https://usabites.co.uk/products/taste-beauty-pepsi-wild-cherry-lip-balm?srsltid=AfmBOoqYSBfDZ0p1xhnhRoPyeolOyfSMDi5xasgP-b06aJku-TBGvmRJ",
        salesRankDrops: "3.44",
        roi: "23.9",
        profit: "$1.09"
    },
    {
        id: 23,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ogt/ogt00086/l/2.jpg",
        keepaChart: "https://graph.keepa.com/graph.png?asin=B084RRSBX4&domain=1&amazon=1",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://uk.iherb.com/pr/organic-traditions-instant-mushroom-coffee-focus-fuel-5-oz-140-g/138741",
        salesRankDrops: "16.51",
        roi: "34.16",
        profit: "$6.51"
    },
    {
        id: 24,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cdn.dolphinfitness.com/tn1/tn1_148276722.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B084RRSBX4",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://www.dolphinfitness.co.uk/en/natural-traditions-focus-fuel-coffee-140g/276722",
        salesRankDrops: "17.59",
        roi: "26.95",
        profit: "$5.43"
    },
    {
        id: 26,
        asin: "B0CVQSDDZJ",
        title: "Panini FIFA 2024 Top Class Blaster Box, Mixed",
        amazonImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL.__AC_SX300_SY300_QL70_ML2_.jpg",
        supplierImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL._AC_SX425_.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0CVQSDDZJ",
        amzPrice: "$28.87",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        storeLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        salesRankDrops: "11.49",
        roi: "42.01",
        profit: "$6.11"
    },
    {
        id: 27,
        asin: "B0BDBCQQW2",
        title: "Ultra Pro | Pokemon Pikachu & Mimikyu 9-Pocket Folder",
        amazonImage: "https://m.media-amazon.com/images/I/81t8iT1SxOL._AC_SX425_.jpg",
        supplierImage: "https://cdn.chaoscards.co.uk/uploads/prod_img/2_220505_e.png?v=-62169983925",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0BDBCQQW2",
        amzPrice: "$28.26",
        storePrice: "$3.00",
        amazonLink: "https://www.amazon.co.uk/Ultra-Pro-Pokemon-Pikachu-Mimikyu/dp/B0BDBCQQW2",
        storeLink: "https://www.chaoscards.co.uk/prod/folders/ultra-pro-pokemon-pikachu-mimikyu-9-pocket-a4-portfolio",
        salesRankDrops: "8.51",
        roi: "45.82",
        profit: "$5.98"
    },
    {
        id: 28,
        asin: "B000RY496K",
        title: "Yankee Candle French Vanilla Small Jar Candle",
        amazonImage: "https://m.media-amazon.com/images/I/518hWlJopTL._AC_SX679_.jpg",
        supplierImage: "https://www.candleemporium.co.uk/images/productzoom/1507745E.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B000RY496K",
        amzPrice: "$20.86",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Yankee-Candle-French-Vanilla-Small/dp/B000RY496K",
        storeLink: "https://www.candleemporium.co.uk/yankee-candle-vanilla-small-jar/p/11008/",
        salesRankDrops: "6.89",
        roi: "24.39",
        profit: "$2.66"
    },
    {
        id: 22,
        asin: "B083JM36RQ",
        title: "Taste Beauty Pepsi Wild Cherry Flavored Lip Balm",
        amazonImage: "https://m.media-amazon.com/images/I/71e3jwUefGL._SX466_.jpg",
        supplierImage: "https://usabites.co.uk/cdn/shop/products/PepsiWildCherry-800x800.png?v=1681811179&width=823",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B083JM36RQ",
        amzPrice: "$10.99",
        storePrice: "$2.00",
        amazonLink: "https://www.amazon.com/dp/B083JM36RQ",
        storeLink: "https://usabites.co.uk/products/taste-beauty-pepsi-wild-cherry-lip-balm?srsltid=AfmBOoqYSBfDZ0p1xhnhRoPyeolOyfSMDi5xasgP-b06aJku-TBGvmRJ",
        salesRankDrops: "3.44",
        roi: "23.9",
        profit: "$1.09"
    },
    {
        id: 23,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ogt/ogt00086/l/2.jpg",
        keepaChart: "https://graph.keepa.com/graph.png?asin=B084RRSBX4&domain=1&amazon=1",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://uk.iherb.com/pr/organic-traditions-instant-mushroom-coffee-focus-fuel-5-oz-140-g/138741",
        salesRankDrops: "16.51",
        roi: "34.16",
        profit: "$6.51"
    },
    {
        id: 24,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cdn.dolphinfitness.com/tn1/tn1_148276722.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B084RRSBX4",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://www.dolphinfitness.co.uk/en/natural-traditions-focus-fuel-coffee-140g/276722",
        salesRankDrops: "17.59",
        roi: "26.95",
        profit: "$5.43"
    },
    {
        id: 26,
        asin: "B0CVQSDDZJ",
        title: "Panini FIFA 2024 Top Class Blaster Box, Mixed",
        amazonImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL.__AC_SX300_SY300_QL70_ML2_.jpg",
        supplierImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL._AC_SX425_.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0CVQSDDZJ",
        amzPrice: "$28.87",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        storeLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        salesRankDrops: "11.49",
        roi: "42.01",
        profit: "$6.11"
    },
    {
        id: 27,
        asin: "B0BDBCQQW2",
        title: "Ultra Pro | Pokemon Pikachu & Mimikyu 9-Pocket Folder",
        amazonImage: "https://m.media-amazon.com/images/I/81t8iT1SxOL._AC_SX425_.jpg",
        supplierImage: "https://cdn.chaoscards.co.uk/uploads/prod_img/2_220505_e.png?v=-62169983925",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0BDBCQQW2",
        amzPrice: "$28.26",
        storePrice: "$3.00",
        amazonLink: "https://www.amazon.co.uk/Ultra-Pro-Pokemon-Pikachu-Mimikyu/dp/B0BDBCQQW2",
        storeLink: "https://www.chaoscards.co.uk/prod/folders/ultra-pro-pokemon-pikachu-mimikyu-9-pocket-a4-portfolio",
        salesRankDrops: "8.51",
        roi: "45.82",
        profit: "$5.98"
    },
    {
        id: 28,
        asin: "B000RY496K",
        title: "Yankee Candle French Vanilla Small Jar Candle",
        amazonImage: "https://m.media-amazon.com/images/I/518hWlJopTL._AC_SX679_.jpg",
        supplierImage: "https://www.candleemporium.co.uk/images/productzoom/1507745E.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B000RY496K",
        amzPrice: "$20.86",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Yankee-Candle-French-Vanilla-Small/dp/B000RY496K",
        storeLink: "https://www.candleemporium.co.uk/yankee-candle-vanilla-small-jar/p/11008/",
        salesRankDrops: "6.89",
        roi: "24.39",
        profit: "$2.66"
    },
    {
        id: 22,
        asin: "B083JM36RQ",
        title: "Taste Beauty Pepsi Wild Cherry Flavored Lip Balm",
        amazonImage: "https://m.media-amazon.com/images/I/71e3jwUefGL._SX466_.jpg",
        supplierImage: "https://usabites.co.uk/cdn/shop/products/PepsiWildCherry-800x800.png?v=1681811179&width=823",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B083JM36RQ",
        amzPrice: "$10.99",
        storePrice: "$2.00",
        amazonLink: "https://www.amazon.com/dp/B083JM36RQ",
        storeLink: "https://usabites.co.uk/products/taste-beauty-pepsi-wild-cherry-lip-balm?srsltid=AfmBOoqYSBfDZ0p1xhnhRoPyeolOyfSMDi5xasgP-b06aJku-TBGvmRJ",
        salesRankDrops: "3.44",
        roi: "23.9",
        profit: "$1.09"
    },
    {
        id: 23,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ogt/ogt00086/l/2.jpg",
        keepaChart: "https://graph.keepa.com/graph.png?asin=B084RRSBX4&domain=1&amazon=1",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://uk.iherb.com/pr/organic-traditions-instant-mushroom-coffee-focus-fuel-5-oz-140-g/138741",
        salesRankDrops: "16.51",
        roi: "34.16",
        profit: "$6.51"
    },
    {
        id: 24,
        asin: "B084RRSBX4",
        title: "Focus Fuel Coffee Organic Traditions 5 oz Powder",
        amazonImage: "https://m.media-amazon.com/images/I/81ZHCnKdA2L._AC_SX679_.jpg",
        supplierImage: "https://cdn.dolphinfitness.com/tn1/tn1_148276722.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B084RRSBX4",
        amzPrice: "$35.43",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Organic-Tradition-Focus-Fuel-Coffee/dp/B084RRSBX4",
        storeLink: "https://www.dolphinfitness.co.uk/en/natural-traditions-focus-fuel-coffee-140g/276722",
        salesRankDrops: "17.59",
        roi: "26.95",
        profit: "$5.43"
    },
    {
        id: 26,
        asin: "B0CVQSDDZJ",
        title: "Panini FIFA 2024 Top Class Blaster Box, Mixed",
        amazonImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL.__AC_SX300_SY300_QL70_ML2_.jpg",
        supplierImage: "https://m.media-amazon.com/images/I/71tl2M4SdjL._AC_SX425_.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0CVQSDDZJ",
        amzPrice: "$28.87",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        storeLink: "https://www.amazon.co.uk/FIFA-2024-Class-Trading-Collection/dp/B0CWSXPLZW",
        salesRankDrops: "11.49",
        roi: "42.01",
        profit: "$6.11"
    },
    {
        id: 27,
        asin: "B0BDBCQQW2",
        title: "Ultra Pro | Pokemon Pikachu & Mimikyu 9-Pocket Folder",
        amazonImage: "https://m.media-amazon.com/images/I/81t8iT1SxOL._AC_SX425_.jpg",
        supplierImage: "https://cdn.chaoscards.co.uk/uploads/prod_img/2_220505_e.png?v=-62169983925",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B0BDBCQQW2",
        amzPrice: "$28.26",
        storePrice: "$3.00",
        amazonLink: "https://www.amazon.co.uk/Ultra-Pro-Pokemon-Pikachu-Mimikyu/dp/B0BDBCQQW2",
        storeLink: "https://www.chaoscards.co.uk/prod/folders/ultra-pro-pokemon-pikachu-mimikyu-9-pocket-a4-portfolio",
        salesRankDrops: "8.51",
        roi: "45.82",
        profit: "$5.98"
    },
    {
        id: 28,
        asin: "B000RY496K",
        title: "Yankee Candle French Vanilla Small Jar Candle",
        amazonImage: "https://m.media-amazon.com/images/I/518hWlJopTL._AC_SX679_.jpg",
        supplierImage: "https://www.candleemporium.co.uk/images/productzoom/1507745E.jpg",
        keepaChart: "https://graph.keepa.com/pricehistory.png?asin=B000RY496K",
        amzPrice: "$20.86",
        storePrice: "$0.00",
        amazonLink: "https://www.amazon.co.uk/Yankee-Candle-French-Vanilla-Small/dp/B000RY496K",
        storeLink: "https://www.candleemporium.co.uk/yankee-candle-vanilla-small-jar/p/11008/",
        salesRankDrops: "6.89",
        roi: "24.39",
        profit: "$2.66"
    }
];
