export const productData = [
    {
        ID: 1,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 2,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 3,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 4,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 5,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 6,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 7,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 8,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 9,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 10,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 11,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 12,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 13,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 14,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    },
    {
        ID: 15,
        ASIN: "B0B9P5MCKL",
        Title: "Age of Sigmar - Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Link : "https://www.amazon.com/dp/B0B9P5MCKL",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 25, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 7,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 2
    },
    {
        ID: 16,
        ASIN: "B0B9P5MCKL",
        Title: "Skaven Deathmaster",
        Image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg",
        Weight: 180,
        ROI: 15,
        Buybox: 21,
        Cost: 18,
        Stores: [
            { name: "Firestorm Games", price: 21, stock: 2, link: "https://firestorm.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Wayland Games", price: 0, stock: 0, link: "https://wayland.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Element Games", price: 24, stock: 10, link: "https://elementgames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Goblin Games", price: 19, stock: 1, link: "https://goblingames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Games Workshop", price: 41.45, stock: 5, link: "https://gamesworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Warlord Workshop", price: 22, stock: 3, link: "https://warlordworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Marionville Games", price: 20, stock: 4, link: "https://marionvillegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "4tk links", price: 23, stock: 5, link: "https://4tk.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Hobby Workshop", price: 25, stock: 6, link: "https://hobbyworkshop.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Magic Madhouse", price: 26, stock: 7, link: "https://magicmadhouse.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Mighty Meele", price: 27, stock: 8, link: "https://mightymeele.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Travelling Man", price: 28, stock: 9, link: "https://travellingman.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" },
            { name: "Beanie Games", price: 29, stock: 10, link: "https://beaniegames.com", image: "https://m.media-amazon.com/images/I/712MWh9F4dL._AC_SX679_.jpg" }
        ],
        BestPrice: 25,
        Profit: 1,
        SalesRank: 120,
        FBA_seller: 3,
        Historic_FBA_sellers: 5,
        FBA_fees: 5,
        Referal_fee: 15,
        Saturation_Score: 8,
        Total_Stock: 0
    }
];
