export const productData = [
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 1,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    {
        ID: 2,
        ASIN: 'B0DVT9Q8Y9',
        Title: 'Games Workshop - Warhammer 40,000 - Astra Militarum: Krieg Heavy Weapons Squad',
        AmazonImage: 'https://m.media-amazon.com/images/I/61xb-v0hUVL._AC_SX679_.jpg',
        SupplierImage: 'https://travellingman.com/cdn/shop/files/https___trade.games-workshop.com_assets_2025_02_99120105130_AstraMilitarumKriegHeavyWeaponsSquad5_1024x1024@2x.jpg?v=1738933863',
        KeepaChart: 'https://graph.keepa.com/pricehistory.png?asin=B0DVT9Q8Y9',
        Amazon: 'https://www.amazon.com/Games-Workshop-Warhammer-Militarum-Weapons/dp/B0DVT9Q8Y9',
        Supplier: 'https://travellingman.com/products/astra-militarum-kreig-heavy-weapons-squad?_pos=1&_sid=cac34b6d9&_ss=r',
        Weight: 1500,
        BuyBoxPrice: 99.99,
        SalesRankDrops: 120,
        HistoricFBASellers: 5,
        ReferralFeePercent: 15,
        Cost: 50,
        Profit: 25,
        ROI: 50,
        FBASellersLive: 3,
        SaturationScore: 6,
        FBAFees: 10,
        TotalStock: 0
    },
    
    
    
];
